package io.smallrye.httpassured.integration.compat;

import io.smallrye.certs.PemCertificateFiles;
import io.smallrye.certs.Format;
import io.smallrye.certs.junit5.Certificate;
import io.smallrye.certs.junit5.Certificates;
import io.smallrye.httpassured.HttpAssured;
import io.smallrye.httpassured.HttpAssuredException;
import io.smallrye.httpassured.engine.vertx.VertxHttpEngine;
import io.smallrye.httpassured.spi.TrustOptions;
import io.vertx.core.Vertx;
import io.vertx.core.http.HttpServer;
import io.vertx.core.http.HttpServerOptions;
import io.vertx.core.net.PemKeyCertOptions;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.handler.BodyHandler;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * REST Assured compatibility tests — HTTPS with self-signed / untrusted certificates.
 *
 * <p>Mirrors the patterns from the Baeldung article
 * <a href="https://www.baeldung.com/rest-assured-https-untrusted">
 * REST Assured with HTTPS and Untrusted Certificates</a>.
 *
 * <p>Uses an embedded Vert.x HTTPS server with a certificate generated by the SmallRye
 * Certificate Generator JUnit 5 extension. WireMock cannot serve TLS, so an embedded
 * Vert.x server is used here — the only exception in this compat test suite.
 *
 * <p><b>API difference (REST Assured vs http-assured):</b>
 * <ul>
 *   <li>REST Assured: {@code RestAssured.useRelaxedHTTPSValidation()} is a one-time static
 *       call that disables certificate validation globally for all subsequent requests.</li>
 *   <li>http-assured: {@code given().trustAll(true)} is per-request, not global.
 *       This is intentional — http-assured has no static mutable state.</li>
 * </ul>
 */
@Certificates(
        baseDir = "target/certs/compat-https",
        certificates = @Certificate(name = "compat-test", formats = Format.PEM))
class HttpsUntrustedCertTest {

    private static final String CERT_NAME = "compat-test";
    private static final Path CERT_DIR = Path.of("target/certs/compat-https");

    private static Vertx vertx;
    private static HttpServer server;
    private static int httpsPort;

    @BeforeAll
    static void startHttpsServer() throws InterruptedException {
        PemCertificateFiles pem = new PemCertificateFiles(CERT_DIR, CERT_NAME, false, null);

        vertx = Vertx.vertx();
        Router router = Router.router(vertx);
        router.route().handler(BodyHandler.create());
        router.get("/hello").handler(ctx ->
                ctx.response()
                        .putHeader("Content-Type", "text/plain")
                        .end("Hello HTTPS"));

        HttpServerOptions options = new HttpServerOptions()
                .setSsl(true)
                .setKeyCertOptions(new PemKeyCertOptions()
                        .setCertPath(pem.certFile().toString())
                        .setKeyPath(pem.keyFile().toString()));

        CountDownLatch latch = new CountDownLatch(1);
        server = vertx.createHttpServer(options).requestHandler(router);
        server.listen(0).onComplete(ar -> {
            if (ar.succeeded()) {
                httpsPort = ar.result().actualPort();
            }
            latch.countDown();
        });
        assertTrue(latch.await(10, TimeUnit.SECONDS), "HTTPS server failed to start");
    }

    @AfterAll
    static void stopHttpsServer() {
        if (server != null) {
            CountDownLatch latch = new CountDownLatch(1);
            server.close().onComplete(v -> latch.countDown());
            try {
                latch.await(5, TimeUnit.SECONDS);
            } catch (InterruptedException ignored) {
            }
        }
        if (vertx != null) {
            CountDownLatch latch = new CountDownLatch(1);
            vertx.close().onComplete(v -> latch.countDown());
            try {
                latch.await(5, TimeUnit.SECONDS);
            } catch (InterruptedException ignored) {
            }
        }
    }

    /**
     * REST Assured equivalent: {@code RestAssured.useRelaxedHTTPSValidation()}.
     * http-assured equivalent: {@code given().trustAll(true)}.
     */
    @Test
    void shouldAcceptSelfSignedCertWithTrustAll() {
        HttpAssured client = HttpAssured.builder()
                .baseUri("https://localhost").port(httpsPort)
                .engine(new VertxHttpEngine(vertx))
                .build();
        try {
            assertDoesNotThrow(() ->
                    client.given()
                            .trustAll(true)
                            .when().get("/hello")
                            .then().statusCode(200));
        } finally {
            client.close();
        }
    }

    /**
     * Without any trust configuration the engine performs standard certificate validation.
     * A self-signed cert is not trusted by the JVM trust store, so the request must fail.
     */
    @Test
    void shouldRejectSelfSignedCertByDefault() {
        HttpAssured client = HttpAssured.builder()
                .baseUri("https://localhost").port(httpsPort)
                .engine(new VertxHttpEngine(vertx))
                .build();
        try {
            assertThrows(HttpAssuredException.class, () ->
                    client.given()
                            .trustAll(false)
                            .when().get("/hello"));
        } finally {
            client.close();
        }
    }

    /**
     * Providing the server's CA certificate in a {@link TrustOptions.Pem} trust store
     * allows the client to validate the chain without disabling all certificate checks.
     */
    @Test
    void shouldAcceptCertWithMatchingTrustStore() {
        PemCertificateFiles pem = new PemCertificateFiles(CERT_DIR, CERT_NAME, false, null);
        TrustOptions opts = TrustOptions.pem(pem.trustStore());

        HttpAssured client = HttpAssured.builder()
                .baseUri("https://localhost").port(httpsPort)
                .engine(new VertxHttpEngine(vertx))
                .build();
        try {
            assertDoesNotThrow(() ->
                    client.given()
                            .trustAll(false)
                            .trustOptions(opts)
                            .when().get("/hello")
                            .then().statusCode(200));
        } finally {
            client.close();
        }
    }
}
