package io.smallrye.httpassured.integration.compat;

import io.smallrye.certs.Format;
import io.smallrye.certs.JksCertificateFiles;
import io.smallrye.certs.PemCertificateFiles;
import io.smallrye.certs.Pkcs12CertificateFiles;
import io.smallrye.certs.junit5.Certificate;
import io.smallrye.certs.junit5.Certificates;
import io.smallrye.httpassured.HttpAssured;
import io.smallrye.httpassured.engine.vertx.VertxHttpEngine;
import io.smallrye.httpassured.spi.TrustOptions;
import io.vertx.core.Vertx;
import io.vertx.core.http.HttpServer;
import io.vertx.core.http.HttpServerOptions;
import io.vertx.core.net.JksOptions;
import io.vertx.core.net.PemKeyCertOptions;
import io.vertx.core.net.PfxOptions;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.handler.BodyHandler;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import static io.smallrye.httpassured.assertion.Assertions.isEqualTo;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * REST Assured compatibility tests — SSL/TLS with JKS and PKCS12 trust stores.
 *
 * <p>Complements {@link HttpsUntrustedCertTest} (which covers PEM trust stores,
 * {@code trustAll(true)}, and untrusted-cert rejection) by exercising the JKS and
 * PKCS12 trust store paths in {@link TrustOptions}, plus an HTTPS GET with JSON
 * body assertions over a trust-all connection.
 *
 * <p>Uses an embedded Vert.x HTTPS server with certificates generated by the SmallRye
 * Certificate Generator JUnit 5 extension.
 */
@Certificates(
        baseDir = "target/certs/compat-ssl",
        certificates = {
                @Certificate(name = "ssl-jks", formats = Format.JKS, password = SslTest.PASSWORD),
                @Certificate(name = "ssl-p12", formats = Format.PKCS12, password = SslTest.PASSWORD),
                @Certificate(name = "ssl-pem", formats = Format.PEM)
        })
class SslTest {

    static final String PASSWORD = "changeit";
    private static final Path CERT_DIR = Path.of("target/certs/compat-ssl");

    @Nested
    class JksTrustStore {

        private static Vertx vertx;
        private static HttpServer server;
        private static int httpsPort;

        @BeforeAll
        static void startServer() throws InterruptedException {
            JksCertificateFiles jks = new JksCertificateFiles(CERT_DIR, "ssl-jks", false, PASSWORD);

            vertx = Vertx.vertx();
            Router router = buildRouter(vertx);

            HttpServerOptions options = new HttpServerOptions()
                    .setSsl(true)
                    .setKeyCertOptions(new JksOptions()
                            .setPath(jks.keyStoreFile().toString())
                            .setPassword(jks.password()));

            CountDownLatch latch = new CountDownLatch(1);
            server = vertx.createHttpServer(options).requestHandler(router);
            server.listen(0).onComplete(ar -> {
                if (ar.succeeded()) {
                    httpsPort = ar.result().actualPort();
                }
                latch.countDown();
            });
            assertTrue(latch.await(10, TimeUnit.SECONDS), "JKS HTTPS server failed to start");
        }

        @AfterAll
        static void stopServer() {
            shutdown(server, vertx);
        }

        @Test
        void shouldAcceptCertWithJksTrustStore() {
            JksCertificateFiles jks = new JksCertificateFiles(CERT_DIR, "ssl-jks", false, PASSWORD);
            TrustOptions opts = TrustOptions.jks(jks.trustStoreFile(), jks.password());

            HttpAssured client = HttpAssured.builder()
                    .baseUri("https://localhost").port(httpsPort)
                    .engine(new VertxHttpEngine(vertx))
                    .build();
            try {
                assertDoesNotThrow(() ->
                        client.given()
                                .trustAll(false)
                                .trustOptions(opts)
                                .when().get("/hello")
                                .then().statusCode(200));
            } finally {
                client.close();
            }
        }
    }

    @Nested
    class Pkcs12TrustStore {

        private static Vertx vertx;
        private static HttpServer server;
        private static int httpsPort;

        @BeforeAll
        static void startServer() throws InterruptedException {
            Pkcs12CertificateFiles p12 = new Pkcs12CertificateFiles(CERT_DIR, "ssl-p12", false, PASSWORD);

            vertx = Vertx.vertx();
            Router router = buildRouter(vertx);

            HttpServerOptions options = new HttpServerOptions()
                    .setSsl(true)
                    .setKeyCertOptions(new PfxOptions()
                            .setPath(p12.keyStoreFile().toString())
                            .setPassword(p12.password()));

            CountDownLatch latch = new CountDownLatch(1);
            server = vertx.createHttpServer(options).requestHandler(router);
            server.listen(0).onComplete(ar -> {
                if (ar.succeeded()) {
                    httpsPort = ar.result().actualPort();
                }
                latch.countDown();
            });
            assertTrue(latch.await(10, TimeUnit.SECONDS), "PKCS12 HTTPS server failed to start");
        }

        @AfterAll
        static void stopServer() {
            shutdown(server, vertx);
        }

        @Test
        void shouldAcceptCertWithPkcs12TrustStore() {
            Pkcs12CertificateFiles p12 = new Pkcs12CertificateFiles(CERT_DIR, "ssl-p12", false, PASSWORD);
            TrustOptions opts = TrustOptions.pkcs12(p12.trustStoreFile(), p12.password());

            HttpAssured client = HttpAssured.builder()
                    .baseUri("https://localhost").port(httpsPort)
                    .engine(new VertxHttpEngine(vertx))
                    .build();
            try {
                assertDoesNotThrow(() ->
                        client.given()
                                .trustAll(false)
                                .trustOptions(opts)
                                .when().get("/hello")
                                .then().statusCode(200));
            } finally {
                client.close();
            }
        }
    }

    @Nested
    class HttpsJsonBody {

        private static Vertx vertx;
        private static HttpServer server;
        private static int httpsPort;

        @BeforeAll
        static void startServer() throws InterruptedException {
            PemCertificateFiles pem = new PemCertificateFiles(CERT_DIR, "ssl-pem", false, null);

            vertx = Vertx.vertx();
            Router router = buildRouter(vertx);

            HttpServerOptions options = new HttpServerOptions()
                    .setSsl(true)
                    .setKeyCertOptions(new PemKeyCertOptions()
                            .setCertPath(pem.certFile().toString())
                            .setKeyPath(pem.keyFile().toString()));

            CountDownLatch latch = new CountDownLatch(1);
            server = vertx.createHttpServer(options).requestHandler(router);
            server.listen(0).onComplete(ar -> {
                if (ar.succeeded()) {
                    httpsPort = ar.result().actualPort();
                }
                latch.countDown();
            });
            assertTrue(latch.await(10, TimeUnit.SECONDS), "PEM HTTPS server failed to start");
        }

        @AfterAll
        static void stopServer() {
            shutdown(server, vertx);
        }

        @Test
        void shouldMakeHttpsGetRequestWithTrustAll() {
            HttpAssured client = HttpAssured.builder()
                    .baseUri("https://localhost").port(httpsPort)
                    .engine(new VertxHttpEngine(vertx))
                    .build();
            try {
                client.given()
                        .trustAll(true)
                        .when().get("/user")
                        .then()
                        .statusCode(200)
                        .body("name", isEqualTo("Alice"))
                        .body("role", isEqualTo("admin"));
            } finally {
                client.close();
            }
        }
    }

    // -- shared helpers --

    private static Router buildRouter(Vertx vertx) {
        Router router = Router.router(vertx);
        router.route().handler(BodyHandler.create());

        router.get("/hello").handler(ctx ->
                ctx.response()
                        .putHeader("Content-Type", "text/plain")
                        .end("Hello HTTPS"));

        router.get("/user").handler(ctx ->
                ctx.response()
                        .putHeader("Content-Type", "application/json")
                        .end("{\"name\":\"Alice\",\"role\":\"admin\"}"));

        return router;
    }

    private static void shutdown(HttpServer server, Vertx vertx) {
        if (server != null) {
            CountDownLatch latch = new CountDownLatch(1);
            server.close().onComplete(v -> latch.countDown());
            try {
                latch.await(5, TimeUnit.SECONDS);
            } catch (InterruptedException ignored) {
            }
        }
        if (vertx != null) {
            CountDownLatch latch = new CountDownLatch(1);
            vertx.close().onComplete(v -> latch.countDown());
            try {
                latch.await(5, TimeUnit.SECONDS);
            } catch (InterruptedException ignored) {
            }
        }
    }
}
